title: Andrew Liew # your name (or website title) here
logo: "/images/gitpage-profile-pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi there! I'm a former Microbiologist turned Data Analyst, with a passion for harnessing the power of natural language processing (NLP), large language models (LLMs), and data visualization to uncover hidden stories in data.
  <br><br>
  <br><br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: # your Google Analytics tracking ID here
